#!/bin/sh

DIR=`pwd`
BUILDDIR=$DIR/build

echo $DIR

if [ ! -d $BUILDDIR ]; then
    mkdir $BUILDDIR
fi

if [ ! -d "vendor" ]; then
    mkdir vendor
fi

if [ ! -d "vendor/httpd-2.2.24" ]; then
    pushd vendor
    curl -O http://mirrors.gigenet.com/apache/httpd/httpd-2.2.24.tar.gz
    tar xvzf httpd-2.2.24.tar.gz
    pushd httpd-2.2.24
    ./configure --prefix=$BUILDDIR \
	        --exec-prefix=$BUILDDIR \
	        --enable-modules=all \
	        --enable-mods-shared=all \
	        --enable-so \
	        --enable-suexec \
	        --enable-ldap \
	        --enable-authnz-ldap \
		--enable-cache --enable-disk-cache --enable-mem-cache --enable-file-cache \
		--enable-ssl --with-ssl \
		--enable-deflate --enable-cgid \
		--enable-proxy --enable-proxy-connect \
		--enable-proxy-http --enable-proxy-ftp \
		--enable-dbd
    make
    make install
    popd
    popd
    pushd $BUILDDIR/conf
    sed -i.bak 's/Listen 80/Listen 8888/' httpd.conf
    sed -i.bak 's/LogLevel warn/LogLevel info/' httpd.conf
    sed -i.bak 's/#ServerName www.example.com:80/ServerName localhost/' httpd.conf
    popd
fi

if [ ! -d "vendor/modsecurity-apache_2.7.2" ]; then
    pushd vendor
    curl -O http://www.modsecurity.org/tarball/2.7.2/modsecurity-apache_2.7.2.tar.gz
    tar xvzf modsecurity-apache_2.7.2.tar.gz
    pushd modsecurity-apache_2.7.2
    ./configure --prefix=$BUILDDIR --exec-prefix=$BUILDDIR
    make
    make install
    cp $BUILDDIR/lib/mod_security2.so $BUILDDIR/modules
    popd
    popd
    mkdir build/conf/modsecurity
    cp -r modsecurity/* build/conf/modsecurity/

    cat <<EOF >> build/conf/httpd.conf
LoadModule security2_module modules/mod_security2.so

<IfModule security2_module>
  Include conf/modsecurity/*.conf
</IfModule>

<IfModule repsheet_module>
  RepsheetEnabled On
  RepsheetAction Notify
  RepsheetPrefix [repsheet]
  RepsheetRedisTimeout 5
  RepsheetRedisHost localhost
  RepsheetRedisPort 6379
  RepsheetRedisTTL 24
  RepsheetRedisMaxLength 2
</IfModule>
EOF
fi
