#!/bin/bash

BLUE="\033[0;34m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
RESET="\033[0;m"

DIR=`pwd`
BUILDDIR=$DIR/build

echo $DIR

if [ ! -d $BUILDDIR ]; then
    mkdir $BUILDDIR
fi

if [ ! -d "vendor" ]; then
    mkdir vendor
fi

if [ ! -d "vendor/nginx-1.4.2" ]; then
    printf "$BLUE * $YELLOW Installing nginx 1.4.2$RESET "
    pushd vendor > /dev/null 2>&1
    curl -s -L -O "http://nginx.org/download/nginx-1.4.2.tar.gz"
    tar xzf "nginx-1.4.2.tar.gz"
    printf "."
    pushd "nginx-1.4.2" > /dev/null 2>&1
    ./configure --with-debug --prefix=`pwd`/../../build/nginx --conf-path=conf/nginx.conf --error-log-path=logs/error.log --http-log-path=logs/access.log --add-module=../../nginx  > install.log 2>&1
    printf "."
    make >> install.log 2>&1
    printf "."
    make install >> install.log 2>&1
    popd > /dev/null 2>&1

    pushd $BUILDDIR/nginx/conf > /dev/null 2>&1
    sed -i.bak 's/listen       80;/listen       8889;/' nginx.conf
    popd > /dev/null 2>&1

    printf "."
    printf " $GREEN [Complete] $RESET\n"
else
    printf "$BLUE * $GREEN nginx already installed $RESET\n"
fi
